<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LT-CHN-33875" name="restassured.automation.testcases.Restassured_Automation_FinancialStatements" tests="11" failures="2" timestamp="13 Jun 2021 05:30:12 GMT" time="102.599" errors="0">
  <testcase name="FinancialStatements_GetFinancialStatementsForTheRevision_Status200" time="6.782" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_LoadTheFinancialStatementsForTheStore_Status200" time="5.533" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_createAnNewFinancialStatementsForTheStore_Status409" time="9.222" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_createAnNewFinancialStatementsForTheStore_Status200" time="5.597" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements">
    <failure type="java.lang.AssertionError" message="expected [200] but found [409]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [409]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_FinancialStatements.FinancialStatements_createAnNewFinancialStatementsForTheStore_Status200(Restassured_Automation_FinancialStatements.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FinancialStatements_createAnNewFinancialStatementsForTheStore_Status200 -->
  <testcase name="FinancialStatements_PatchTheFinancialStatementsLineItems_Status404" time="5.740" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_MoveFinancialStatementsLineItems_Status404" time="15.762" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_createAnNewFinancialStatementsForTheStore_Status400" time="6.346" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_PatchFinancialStatementsForTheRevision_Status400" time="24.983" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_PatchTheFinancialStatementsLineItems_Status409" time="8.621" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_PatchTheFinancialStatementsLineItems_Status400" time="7.415" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements"/>
  <testcase name="FinancialStatements_PatchTheFinancialStatementsLineItems_Status200" time="6.598" classname="restassured.automation.testcases.Restassured_Automation_FinancialStatements">
    <failure type="java.lang.AssertionError" message="expected [204] but found [409]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [409]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_FinancialStatements.FinancialStatements_PatchTheFinancialStatementsLineItems_Status200(Restassured_Automation_FinancialStatements.java:257)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FinancialStatements_PatchTheFinancialStatementsLineItems_Status200 -->
</testsuite> <!-- restassured.automation.testcases.Restassured_Automation_FinancialStatements -->
